import { Router, type IRouter } from "express";

const router: IRouter = Router();

export interface Country {
  id: number;
  name: string;
  code: string;
}

export interface State {
  id: number;
  countryId: number;
  name: string;
}

export const COUNTRIES: Country[] = [
  { id: 1, name: "Nigeria", code: "NG" },
  { id: 2, name: "Ghana", code: "GH" },
  { id: 3, name: "Côte d'Ivoire", code: "CI" },
  { id: 4, name: "Senegal", code: "SN" },
  { id: 5, name: "Cameroon", code: "CM" },
  { id: 6, name: "Benin", code: "BJ" },
  { id: 7, name: "Togo", code: "TG" },
  { id: 8, name: "Mali", code: "ML" },
  { id: 9, name: "Burkina Faso", code: "BF" },
  { id: 10, name: "Niger", code: "NE" },
  { id: 11, name: "Guinea", code: "GN" },
  { id: 12, name: "Sierra Leone", code: "SL" },
  { id: 13, name: "Liberia", code: "LR" },
  { id: 14, name: "Gambia", code: "GM" },
  { id: 15, name: "Guinea-Bissau", code: "GW" },
  { id: 16, name: "Cape Verde", code: "CV" },
  { id: 17, name: "Mauritania", code: "MR" },
  { id: 18, name: "South Africa", code: "ZA" },
  { id: 19, name: "Kenya", code: "KE" },
  { id: 20, name: "Tanzania", code: "TZ" },
  { id: 21, name: "Uganda", code: "UG" },
  { id: 22, name: "Ethiopia", code: "ET" },
  { id: 23, name: "Rwanda", code: "RW" },
  { id: 24, name: "Egypt", code: "EG" },
  { id: 25, name: "Morocco", code: "MA" },
  { id: 26, name: "Tunisia", code: "TN" },
  { id: 27, name: "Algeria", code: "DZ" },
  { id: 28, name: "Libya", code: "LY" },
  { id: 29, name: "Sudan", code: "SD" },
  { id: 30, name: "Angola", code: "AO" },
  { id: 31, name: "Zimbabwe", code: "ZW" },
  { id: 32, name: "Zambia", code: "ZM" },
  { id: 33, name: "Mozambique", code: "MZ" },
  { id: 34, name: "Botswana", code: "BW" },
  { id: 35, name: "Namibia", code: "NA" },
  { id: 36, name: "United Kingdom", code: "GB" },
  { id: 37, name: "United States", code: "US" },
  { id: 38, name: "Canada", code: "CA" },
  { id: 39, name: "France", code: "FR" },
  { id: 40, name: "Germany", code: "DE" },
  { id: 41, name: "Italy", code: "IT" },
  { id: 42, name: "Spain", code: "ES" },
  { id: 43, name: "Portugal", code: "PT" },
  { id: 44, name: "Netherlands", code: "NL" },
  { id: 45, name: "Belgium", code: "BE" },
  { id: 46, name: "Switzerland", code: "CH" },
  { id: 47, name: "Sweden", code: "SE" },
  { id: 48, name: "Norway", code: "NO" },
  { id: 49, name: "Denmark", code: "DK" },
  { id: 50, name: "Finland", code: "FI" },
  { id: 51, name: "Australia", code: "AU" },
  { id: 52, name: "New Zealand", code: "NZ" },
  { id: 53, name: "India", code: "IN" },
  { id: 54, name: "China", code: "CN" },
  { id: 55, name: "Japan", code: "JP" },
  { id: 56, name: "South Korea", code: "KR" },
  { id: 57, name: "Brazil", code: "BR" },
  { id: 58, name: "Argentina", code: "AR" },
  { id: 59, name: "Mexico", code: "MX" },
  { id: 60, name: "United Arab Emirates", code: "AE" },
];

export const STATES: State[] = [
  // Nigeria (1)
  { id: 101, countryId: 1, name: "Abia" },
  { id: 102, countryId: 1, name: "Adamawa" },
  { id: 103, countryId: 1, name: "Akwa Ibom" },
  { id: 104, countryId: 1, name: "Anambra" },
  { id: 105, countryId: 1, name: "Bauchi" },
  { id: 106, countryId: 1, name: "Bayelsa" },
  { id: 107, countryId: 1, name: "Benue" },
  { id: 108, countryId: 1, name: "Borno" },
  { id: 109, countryId: 1, name: "Cross River" },
  { id: 110, countryId: 1, name: "Delta" },
  { id: 111, countryId: 1, name: "Ebonyi" },
  { id: 112, countryId: 1, name: "Edo" },
  { id: 113, countryId: 1, name: "Ekiti" },
  { id: 114, countryId: 1, name: "Enugu" },
  { id: 115, countryId: 1, name: "FCT (Abuja)" },
  { id: 116, countryId: 1, name: "Gombe" },
  { id: 117, countryId: 1, name: "Imo" },
  { id: 118, countryId: 1, name: "Jigawa" },
  { id: 119, countryId: 1, name: "Kaduna" },
  { id: 120, countryId: 1, name: "Kano" },
  { id: 121, countryId: 1, name: "Katsina" },
  { id: 122, countryId: 1, name: "Kebbi" },
  { id: 123, countryId: 1, name: "Kogi" },
  { id: 124, countryId: 1, name: "Kwara" },
  { id: 125, countryId: 1, name: "Lagos" },
  { id: 126, countryId: 1, name: "Nasarawa" },
  { id: 127, countryId: 1, name: "Niger" },
  { id: 128, countryId: 1, name: "Ogun" },
  { id: 129, countryId: 1, name: "Ondo" },
  { id: 130, countryId: 1, name: "Osun" },
  { id: 131, countryId: 1, name: "Oyo" },
  { id: 132, countryId: 1, name: "Plateau" },
  { id: 133, countryId: 1, name: "Rivers" },
  { id: 134, countryId: 1, name: "Sokoto" },
  { id: 135, countryId: 1, name: "Taraba" },
  { id: 136, countryId: 1, name: "Yobe" },
  { id: 137, countryId: 1, name: "Zamfara" },
  // Ghana (2)
  { id: 201, countryId: 2, name: "Ashanti" },
  { id: 202, countryId: 2, name: "Brong-Ahafo" },
  { id: 203, countryId: 2, name: "Central" },
  { id: 204, countryId: 2, name: "Eastern" },
  { id: 205, countryId: 2, name: "Greater Accra" },
  { id: 206, countryId: 2, name: "Northern" },
  { id: 207, countryId: 2, name: "Upper East" },
  { id: 208, countryId: 2, name: "Upper West" },
  { id: 209, countryId: 2, name: "Volta" },
  { id: 210, countryId: 2, name: "Western" },
  // Côte d'Ivoire (3)
  { id: 301, countryId: 3, name: "Abidjan" },
  { id: 302, countryId: 3, name: "Bas-Sassandra" },
  { id: 303, countryId: 3, name: "Comoé" },
  { id: 304, countryId: 3, name: "Denguélé" },
  { id: 305, countryId: 3, name: "Gôh-Djiboua" },
  { id: 306, countryId: 3, name: "Lacs" },
  { id: 307, countryId: 3, name: "Lagunes" },
  { id: 308, countryId: 3, name: "Montagnes" },
  { id: 309, countryId: 3, name: "Sassandra-Marahoué" },
  { id: 310, countryId: 3, name: "Savanes" },
  { id: 311, countryId: 3, name: "Vallée du Bandama" },
  { id: 312, countryId: 3, name: "Woroba" },
  { id: 313, countryId: 3, name: "Yamoussoukro" },
  { id: 314, countryId: 3, name: "Zanzan" },
  // Senegal (4)
  { id: 401, countryId: 4, name: "Dakar" },
  { id: 402, countryId: 4, name: "Diourbel" },
  { id: 403, countryId: 4, name: "Fatick" },
  { id: 404, countryId: 4, name: "Kaffrine" },
  { id: 405, countryId: 4, name: "Kaolack" },
  { id: 406, countryId: 4, name: "Kédougou" },
  { id: 407, countryId: 4, name: "Kolda" },
  { id: 408, countryId: 4, name: "Louga" },
  { id: 409, countryId: 4, name: "Matam" },
  { id: 410, countryId: 4, name: "Saint-Louis" },
  { id: 411, countryId: 4, name: "Sédhiou" },
  { id: 412, countryId: 4, name: "Tambacounda" },
  { id: 413, countryId: 4, name: "Thiès" },
  { id: 414, countryId: 4, name: "Ziguinchor" },
  // Cameroon (5)
  { id: 501, countryId: 5, name: "Adamawa" },
  { id: 502, countryId: 5, name: "Centre" },
  { id: 503, countryId: 5, name: "East" },
  { id: 504, countryId: 5, name: "Far North" },
  { id: 505, countryId: 5, name: "Littoral" },
  { id: 506, countryId: 5, name: "North" },
  { id: 507, countryId: 5, name: "Northwest" },
  { id: 508, countryId: 5, name: "South" },
  { id: 509, countryId: 5, name: "Southwest" },
  { id: 510, countryId: 5, name: "West" },
  // South Africa (18)
  { id: 1801, countryId: 18, name: "Eastern Cape" },
  { id: 1802, countryId: 18, name: "Free State" },
  { id: 1803, countryId: 18, name: "Gauteng" },
  { id: 1804, countryId: 18, name: "KwaZulu-Natal" },
  { id: 1805, countryId: 18, name: "Limpopo" },
  { id: 1806, countryId: 18, name: "Mpumalanga" },
  { id: 1807, countryId: 18, name: "Northern Cape" },
  { id: 1808, countryId: 18, name: "North West" },
  { id: 1809, countryId: 18, name: "Western Cape" },
  // Kenya (19)
  { id: 1901, countryId: 19, name: "Nairobi" },
  { id: 1902, countryId: 19, name: "Mombasa" },
  { id: 1903, countryId: 19, name: "Kisumu" },
  { id: 1904, countryId: 19, name: "Nakuru" },
  { id: 1905, countryId: 19, name: "Eldoret" },
  { id: 1906, countryId: 19, name: "Coast" },
  { id: 1907, countryId: 19, name: "Central" },
  { id: 1908, countryId: 19, name: "Rift Valley" },
  { id: 1909, countryId: 19, name: "Western" },
  { id: 1910, countryId: 19, name: "Nyanza" },
  // United Kingdom (36)
  { id: 3601, countryId: 36, name: "England" },
  { id: 3602, countryId: 36, name: "Scotland" },
  { id: 3603, countryId: 36, name: "Wales" },
  { id: 3604, countryId: 36, name: "Northern Ireland" },
  // United States (37)
  { id: 3701, countryId: 37, name: "Alabama" },
  { id: 3702, countryId: 37, name: "Alaska" },
  { id: 3703, countryId: 37, name: "Arizona" },
  { id: 3704, countryId: 37, name: "Arkansas" },
  { id: 3705, countryId: 37, name: "California" },
  { id: 3706, countryId: 37, name: "Colorado" },
  { id: 3707, countryId: 37, name: "Connecticut" },
  { id: 3708, countryId: 37, name: "Delaware" },
  { id: 3709, countryId: 37, name: "Florida" },
  { id: 3710, countryId: 37, name: "Georgia" },
  { id: 3711, countryId: 37, name: "Hawaii" },
  { id: 3712, countryId: 37, name: "Idaho" },
  { id: 3713, countryId: 37, name: "Illinois" },
  { id: 3714, countryId: 37, name: "Indiana" },
  { id: 3715, countryId: 37, name: "Iowa" },
  { id: 3716, countryId: 37, name: "Kansas" },
  { id: 3717, countryId: 37, name: "Kentucky" },
  { id: 3718, countryId: 37, name: "Louisiana" },
  { id: 3719, countryId: 37, name: "Maine" },
  { id: 3720, countryId: 37, name: "Maryland" },
  { id: 3721, countryId: 37, name: "Massachusetts" },
  { id: 3722, countryId: 37, name: "Michigan" },
  { id: 3723, countryId: 37, name: "Minnesota" },
  { id: 3724, countryId: 37, name: "Mississippi" },
  { id: 3725, countryId: 37, name: "Missouri" },
  { id: 3726, countryId: 37, name: "Montana" },
  { id: 3727, countryId: 37, name: "Nebraska" },
  { id: 3728, countryId: 37, name: "Nevada" },
  { id: 3729, countryId: 37, name: "New Hampshire" },
  { id: 3730, countryId: 37, name: "New Jersey" },
  { id: 3731, countryId: 37, name: "New Mexico" },
  { id: 3732, countryId: 37, name: "New York" },
  { id: 3733, countryId: 37, name: "North Carolina" },
  { id: 3734, countryId: 37, name: "North Dakota" },
  { id: 3735, countryId: 37, name: "Ohio" },
  { id: 3736, countryId: 37, name: "Oklahoma" },
  { id: 3737, countryId: 37, name: "Oregon" },
  { id: 3738, countryId: 37, name: "Pennsylvania" },
  { id: 3739, countryId: 37, name: "Rhode Island" },
  { id: 3740, countryId: 37, name: "South Carolina" },
  { id: 3741, countryId: 37, name: "South Dakota" },
  { id: 3742, countryId: 37, name: "Tennessee" },
  { id: 3743, countryId: 37, name: "Texas" },
  { id: 3744, countryId: 37, name: "Utah" },
  { id: 3745, countryId: 37, name: "Vermont" },
  { id: 3746, countryId: 37, name: "Virginia" },
  { id: 3747, countryId: 37, name: "Washington" },
  { id: 3748, countryId: 37, name: "West Virginia" },
  { id: 3749, countryId: 37, name: "Wisconsin" },
  { id: 3750, countryId: 37, name: "Wyoming" },
  // Canada (38)
  { id: 3801, countryId: 38, name: "Alberta" },
  { id: 3802, countryId: 38, name: "British Columbia" },
  { id: 3803, countryId: 38, name: "Manitoba" },
  { id: 3804, countryId: 38, name: "New Brunswick" },
  { id: 3805, countryId: 38, name: "Newfoundland and Labrador" },
  { id: 3806, countryId: 38, name: "Nova Scotia" },
  { id: 3807, countryId: 38, name: "Ontario" },
  { id: 3808, countryId: 38, name: "Prince Edward Island" },
  { id: 3809, countryId: 38, name: "Quebec" },
  { id: 3810, countryId: 38, name: "Saskatchewan" },
  // Australia (51)
  { id: 5101, countryId: 51, name: "Australian Capital Territory" },
  { id: 5102, countryId: 51, name: "New South Wales" },
  { id: 5103, countryId: 51, name: "Northern Territory" },
  { id: 5104, countryId: 51, name: "Queensland" },
  { id: 5105, countryId: 51, name: "South Australia" },
  { id: 5106, countryId: 51, name: "Tasmania" },
  { id: 5107, countryId: 51, name: "Victoria" },
  { id: 5108, countryId: 51, name: "Western Australia" },
];

router.get("/geo/countries", (_req, res): void => {
  res.json(COUNTRIES);
});

router.get("/geo/states", (req, res): void => {
  const countryId = parseInt(req.query.countryId as string, 10);
  if (!countryId || isNaN(countryId)) {
    res.status(400).json({ error: "countryId query param is required" });
    return;
  }
  const states = STATES.filter(s => s.countryId === countryId);
  res.json(states);
});

export default router;
